### ISSUE TITLE
Error in configuration when loading epm

### ISSUE THREAD

**Issue by pjwest** [eprintsug/rioxx2#18]
Actions taken:
1. disable and install v1.0.1 version of the plugin 
2. download epm from github
3. install plugin via admin screen

(N.B. the reporting framework was not modified)
as the plugin was loaded a config error was reported:

EPrints System Error

Error in configuration:
Global symbol "@problems" requires explicit package name at /usr/share/eprints3/archives/rioxx2/cfg/cfg.d/zz_rioxx2.pl line 549.

**Comment by drtjmb** [comment]
https://github.com/eprintsug/rioxx2/commit/76fcc5ea192012bc066eff949d6ca424c7d4d1bc
