### ISSUE TITLE
rioxx tab on EPrint view item page visible to non-admins

### ISSUE THREAD

**Issue by drn05r** [eprintsug/rioxx2#20]
If a full text has been uploaded for an EPrint if the user who created the EPrint accesses the view item page, they can see the rioxx tab, even though this should only be accessible to admins.

**Comment by drtjmb** [comment]
Does this only happen if a full text is uploaded? If a normal user creates a new item then immediately hits save and exit, does the tab show?

Please test and comment back.

Tim

On 11 Mar 2015 09:29, David R Newman <notifications@github.com> wrote:

If a full text has been uploaded for an EPrint if the user who created the EPrint accesses the view item page, they can see the rioxx tab, even though this should only be accessible to admins.
