### ISSUE TITLE
RIOXX2 XML export not reflecting changes made to the item

### ISSUE THREAD

**Issue by agcox** [eprintsug/rioxx2#33]
(In a test environment) I have created an eprint and saved it without making it live. The default derivation for rioxx authors was accepted

I then revisited the rioxx stage of the workflow and chose to override the author derivation and enter a different author (with ORCID). The eprint was saved without making live.

On exporting the RIOXX2 XML I see that it contains the previous set of authors, rather than the newly entered author. In contrast the EP3 XML export reflects the change.

Similar behaviour occurs if the project is changed.

I haven't tested the behaviour of the other fields.

**Comment by drtjmb** [comment]
I haven't been able to reproduce this - I did the following:

1) New Item
2) Go to Details stage and enter 2 creators, Alice and Bob
3) Save and Return
4) Go to rioxx tab and click View RIOXX2 record
5) Alice and Bob appear as rioxxterms:author
6) Actions -> Edit Item
7) Go to rioxx stage
8) On the Author field click the Override option
9) Enter 2 authors at random, using the ORCID lookup
10) Save and Return
11) Go to rioxx tab and click View RIOXX2 record
12) 2 new authors appear as rioxxterms:author

**Comment by drtjmb** [comment]
@agcox - if you go through the process above do the creators appear as expected at step 4?

**Comment by agcox** [comment]
Weird. Following your steps shows it working as designed - and, yes, the creators appear as expected at step 4, changing as they should at 11.

I will review and return with a minimal recipe to reproduce the issue.

I have just re-exported the RIOXX2 record on the item that showed the problem and now find that it is correct - consistent with the eprint. Fortunately for my sanity I also have PDFs showing the previously inconsistent details screen and RIOXX2 record.

As I said, I will attempt to reproduce and report back.

**Comment by drtjmb** [comment]
Was the first rioxx export cached perhaps?

Tim

On 10 Sep 2015 12:10 pm, "Alan Cox (but not the Linux one)" <notifications@github.com> wrote:

Weird. Following your steps shows it working as designed - and, yes, the creators appear as expected at step 4, changing as they should at 11.

I will review and return with a minimal recipe to reproduce the issue.

I have just re-exported the RIOXX2 record on the item that showed the problem and now find that it is correct - consistent with the eprint. Fortunately for my sanity I also have PDFs showing the previously inconsistent details screen and RIOXX2 record.

As I said, I will attempt to reproduce and report back.

**Comment by agcox** [comment]
I've spent enough time failing to reproduce this that I'm prepared to put it down to malign spirits and close it.
